on:
  workflow_dispatch:
    inputs:
      firstPlayerUrl:
        description: "First player url"
        required: true
      secondPlayerUrl:
        description: "Second player url"
        required: true
name: Render video
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install virtual display
        run: sudo apt-get install -yq --no-install-recommends xvfb xauth ffmpeg libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 libnss3
      
      - name: Install full Google Chrome
        run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && sudo apt install ./google-chrome-stable_current_amd64.deb -y

      - name: Exports chrome bin path to ENV
        run: export CHROME_BIN=$(which google-chrome) && export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm install && cd remotion-video && npm install && cd ..
      - run: npm start -- --firstPlayerUrl="${{github.event.inputs.firstPlayerUrl}}" --secondPlayerUrl="${{github.event.inputs.secondPlayerUrl}}"
      - uses: actions/upload-artifact@v2
        with:
          name: out.mp4
          path: remotion-video/out.mp4
